#!/bin/bash

function abort
{
   echo "$@" 1>&2
   exit 1
}

# REPO=${REGISTRY_PORT/tcp:\/\//}
REPO=${REPO:-localhost:5000}
NAME=${NAME:-storage}
[ $TAG ] || abort "TAG env is missing."

docker run --name storage_$TAG --volumes-from $HOSTNAME subak/storage backup $@
docker commit storage_$TAG $REPO/$NAME:$TAG
docker push $REPO/$NAME:$TAG
docker rm storage_$TAG
docker rmi $REPO/$NAME:$TAG
