#!/bin/bash

function abort
{
   echo "$@" 1>&2
   exit 1
}

# REPO=${REGISTRY_PORT/tcp:\/\//}
REPO=${REPO:-localhost:5000}
NAME=${NAME:-storage}
[ $TAG ] || abort "TAG env is missing."

docker pull $REPO/$NAME:$TAG
docker run --rm --volumes-from $HOSTNAME $REPO/$NAME:$TAG restore $@
docker rmi $REPO/$NAME:$TAG
