#!/bin/bash

if [ -n "$AUTH_DATA" ]; then
  echo $AUTH_DATA > /root/.docker/config.json
fi

function abort
{
   echo "$@" 1>&2
   exit 1
}

REGI=${REGI:-docker.io}
[ "$REPO" ] || abort "REPO env is missing."
[ "$TAG" ] || abort "TAG env is missing."

docker pull $REGI/$REPO:$TAG
docker run --rm --volumes-from $HOSTNAME $REGI/$REPO:$TAG restore $@
docker rmi $REGI/$REPO:$TAG
