#!/bin/bash

set -ue

if [ -n "$AUTH_DATA" ]; then
  echo $AUTH_DATA > /root/.docker/config.json
fi

function abort
{
   echo "$@" 1>&2
   exit 1
}

REGI=${REGI:-docker.io}
TAG_SUFFIX=${TAG_SUFFIX:-''}

name=$(mkpasswd -m md5 '' | base64 | sed 's/[=+\/]//g')
image="${REGI}/${REPO}:${TAG}${TAG_SUFFIX}"

docker run --name ${name} --volumes-from ${HOSTNAME} subak/storage backup $@
iid=$(docker commit ${name} ${image})
# TODO: handle unauthorized error
docker push ${image}
docker rm -v ${name}
docker rmi -f ${iid}
