#!/bin/bash

set -ue

if [ -n "$AUTH_DATA" ]; then
  echo $AUTH_DATA > /root/.docker/config.json
fi

function abort
{
   echo "$@" 1>&2
   exit 1
}

REGI=${REGI:-docker.io}
TAG_SUFFIX=${TAG_SUFFIX:-''}
NAME=$(mkpasswd -m md5 '' | base64 | sed 's/[=+\/]//g')

docker run --name $NAME --volumes-from $HOSTNAME subak/storage backup $@
docker commit $NAME $REGI/$REPO:$TAG$TAG_SUFFIX
# TODO: handle unauthorized error
docker push $REGI/$REPO:$TAG$TAG_SUFFIX
docker rm $NAME
docker rmi $REGI/$REPO:$TAG$TAG_SUFFIX
