cron:
  image: subak/cron:latest
  environment:
    REGI: localhost:5000
    AUTH_DATA: '{"auths":{}}'
    REPO: my/storage
    TAG: default
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - storage
  command:
    - 00 05 * * * TAG=$TAG-$(date +%u) /backup /path/to/target

backup:
  image: subak/cron:latest
  environment:
    REGI: localhost:5000
    AUTH_DATA: '{"auths":{}}'
    REPO: my/storage
    TAG: default
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - storage
  entrypoint: /backup
  command:
    - /path/to/target
